<a href="https://colab.research.google.com/github/lejejefr/ECM_2526_FinalProject/blob/main/Sripts/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#ce script sert à explorer les données

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
url = 'https://raw.githubusercontent.com/lejejefr/ECM_2526_FinalProject/refs/heads/main/Data/RawData.csv'
df = pd.read_csv(url)
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,28910,JJ442189,10/06/2025 05:19:00 PM,016XX W 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,False,False,...,17.0,71.0,01A,1166608.0,1852321.0,2025,10/14/2025 03:58:46 PM,41.750334,-87.665045,"(41.75033427, -87.665045312)"
1,28909,JJ442109,10/06/2025 05:15:00 PM,000XX N KILBOURN AVE,110,HOMICIDE,FIRST DEGREE MURDER,GAS STATION,False,False,...,28.0,26.0,01A,1146387.0,1899777.0,2025,10/14/2025 03:58:46 PM,41.880968,-87.737940,"(41.88096768, -87.737940272)"
2,28908,JJ441599,10/06/2025 09:17:00 AM,056XX W WASHINGTON BLVD,110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,False,True,...,29.0,25.0,01A,1138415.0,1900175.0,2025,10/14/2025 03:58:46 PM,41.882208,-87.767204,"(41.88220788, -87.767203679)"
3,28907,JJ441303,10/06/2025 03:36:00 AM,026XX W 39TH PL,110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,12.0,58.0,01A,1159522.0,1878370.0,2025,10/14/2025 03:58:46 PM,41.821964,-87.690298,"(41.821964415, -87.690297894)"
4,28906,JJ439875,10/04/2025 08:35:00 PM,038XX W ROOSEVELT RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,False,False,...,24.0,29.0,01A,1151170.0,1894442.0,2025,10/12/2025 03:43:35 PM,41.866235,-87.720517,"(41.866235446, -87.720517147)"

In [10]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13977 entries, 0 to 13976
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    13977 non-null  int64
 1   Case Number           13977 non-null  object
 2   Date                  13977 non-null  object
 3   Block                 13977 non-null  object
 4   IUCR                  13977 non-null  int64
 5   Primary Type          13977 non-null  object
 6   Description           13977 non-null  object
 7   Location Description  13977 non-null  object
 8   Arrest                13977 non-null  bool
 9   Domestic              13977 non-null  bool
 10  Beat                  13977 non-null  int64
 11  District              13977 non-null  int64
 12  Ward                  13597 non-null  float64
 13  Community Area        13597 non-null  float64
 14  FBI Code              13977 non-null  object
 15  X Coordinate          13974 non-null  float64
 16  Y Coordinate          13974 non-null  float64
 17  Year                  13977 non-null  int64
 18  Updated On            13977 non-null  object
 19  Latitude              13974 non-null  float64
 20  Longitude             13974 non-null  float64
 21  Location              13974 non-null  object
dtypes: bool(2), float64(6), int64(5), object(9)
memory usage: 2.2+ MB

,ID,IUCR,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
count,1.397700e+04,13977.000000,13977.000000,13977.000000,13597.000000,13597.000000,1.397400e+04,1.397400e+04,13977.000000,13974.000000,13974.000000
mean,8.266806e+04,110.197897,1022.846462,9.895328,19.834890,42.507097,1.162489e+06,1.871749e+06,2013.432568,41.803527,-87.678826
std,8.591178e+05,2.502698,619.716793,6.146570,11.507542,19.427202,6.194231e+04,1.005784e+05,7.342687,0.278424,0.214317
min,6.340000e+02,110.000000,111.000000,1.000000,1.000000,1.000000,0.000000e+00,0.000000e+00,2001.000000,36.619446,-91.686566
25%,4.130000e+03,110.000000,533.000000,5.000000,9.000000,26.000000,1.152574e+06,1.854764e+06,2007.000000,41.756634,-87.715184
50%,2.175900e+04,110.000000,915.000000,9.000000,20.000000,43.000000,1.166350e+06,1.871643e+06,2015.000000,41.803265,-87.665442
75%,2.540400e+04,110.000000,1233.000000,12.000000,28.000000,61.000000,1.177538e+06,1.899709e+06,2020.000000,41.880751,-87.624720
max,1.373461e+07,142.000000,2535.000000,25.000000,50.000000,77.000000,1.204790e+06,1.951492e+06,2025.000000,42.022548,-87.525759

In [11]:
df.isnull().sum()

ID                        0
Case Number               0
Date                      0
Block                     0
IUCR                      0
Primary Type              0
Description               0
Location Description      0
Arrest                    0
Domestic                  0
Beat                      0
District                  0
Ward                    380
Community Area          380
FBI Code                  0
X Coordinate              3
Y Coordinate              3
Year                      0
Updated On                0
Latitude                  3
Longitude                 3
Location                  3
dtype: int64

In [12]:
df.nunique()

ID                      13977
Case Number             13373
Date                    13690
Block                    8114
IUCR                        4
Primary Type                1
Description                 4
Location Description       93
Arrest                      2
Domestic                    2
Beat                      296
District                   22
Ward                       50
Community Area             77
FBI Code                    2
X Coordinate            10820
Y Coordinate            11365
Year                       25
Updated On               1319
Latitude                12555
Longitude               12554
Location                12555
dtype: int64